browser = "Chrome"
url ="https://www.myntra.com/"
mobile_no = 7411964919
item_name = "Kurta"
invalid_items = "hksdbvznvzmnczm"
mens_shirt = "Men Shirts"
size = "M"
quantity = 2
gender = "Men"
symbol = "₹"